services:
  web:
    image: nginx:latest
    ports:
      - "8083:80"
    networks:
      - mynetwork

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: labpassword
      MYSQL_DATABASE: lab_db
    ports:
      - "3308:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
