services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    networks:
      - mynetwork

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
      MYSQL_DATABASE: dev_db
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
