services:
  web:
    image: nginx:latest
    ports:
      - "8082:80"
    networks:
      - mynetwork

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: prodpassword
      MYSQL_DATABASE: prod_db
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
